### ISSUE TITLE
Create the CheckBox component

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#26]
https://kiwicom.github.io/orbit-components/?selectedKind=CheckBox&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by RobinCsl** [comment]
You can also take inspiration from
https://github.com/kiwicom/mobile/blob/master/packages/shared/src/forms/Checkbox.js

**Comment by JoseDuSV** [comment]
Remaining Checkbox tasks
- [ ] add tests
- [ ] add accessibility
- [ ] storybook - add `With TextLink in label` _(TextLink component needed)_
- [ ] consider what to do with currently unused `value` + `name` props in **native**
- [ ] decide about `onPress -> onChange` implementation for **native**

Styles related tasks:
- [ ] `CheckboxText` - info `lineHeight` should be `theme.orbit.lineHeightText` _(returns value 1.4)_ but RNW keeps adding `px` for web
- [ ] implement hover style (just for **web**): `border-color: theme.orbit.borderColorCheckboxRadioHover`
- [ ] implement focus style: `outline: 0; borderWidth: 2; border-color: theme.orbit.borderColorCheckboxRadioFocus`
- [ ] implement transitions (at least for **web**): `transition: all theme.orbit.durationFast ease-in-out;` _(probably just for border color instead of 'all')_
- [ ] implement `active` scale from original component (if needed) `!disabled && scale(theme.orbit.modifierScaleCheckboxRadioActive)`
- [ ] implement `active` border color: `disabled ? getToken(TOKENS.borderColor) : theme.orbit.borderColorCheckboxRadioActive`

**Comment by RobinCsl** [comment]
@JoseDuSV Could you create 3 separate issues for the remaining enhancements for that component and mention this issue in there? I think we should close this one.
